### ISSUE TITLE
Unknown obstacles error

### ISSUE THREAD

**Issue by darkobozhinoski** [rosin-project/metacontrol_experiments#10] opened 2020-05-23 10:53 UTC
When I run the experimental setup, I am getting the following error.

`./run_single_sim.sh -i 2 -g 2 -n f1_v3_r1  -r true -p 1.2`

```
Traceback (most recent call last):
  File "/home/darko/metancontrol_ws/src/metacontrol_experiments/scripts/create_unknown_obstacles.py", line 77, in <module>
    if not check_obstacle_existence('unknown_obstacle' + str(obs_nr)):
  File "/home/darko/metancontrol_ws/src/metacontrol_experiments/scripts/create_unknown_obstacles.py", line 34, in check_obstacle_existence
    check_obstacle_response = check_obstacle_service(obstacle_name)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 442, in __call__
    return self.call(*args, **kwds)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 502, in call
    service_uri = self._get_service_uri(request)
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_service.py", line 470, in _get_service_uri
    raise ServiceException("service [%s] unavailable"%self.resolved_name)
rospy.service.ServiceException: service [/gazebo/get_model_properties] unavailable
```

**Comment by chcorbato** [comment] 2020-05-23 10:58
Ok, @darkobozhinoski try to triage the issue when you create it:

- **assign** it if you have a clear idea who can look into the issue, 
- set any label to indicate if it is a PRIOrity, enhancement or wontfix (things we want to remember for later)
- set it to a project if relevant, so we see them in the board. For our issues these days, `MVP ...`

If you are not sure about the triage, or want people to look at it to discuss, you can mention people in the issue

**Comment by marioney** [comment] 2020-05-24 11:15
I think this error was caused by an exception when checking the obstacles in gazebo.
 This should be solved by https://github.com/rosin-project/metacontrol_experiments/commit/a5f96b4f9761fb6199bcccd979cff0fa338707a1

Since the error very uncommon. I'll leave this open and I'll close if I get to run the full batch of experiments without that error appearing

**Comment by chcorbato** [comment] 2021-04-02 11:48
I close it, since it has not been reported again.

**Closed as completed by chcorbato** 2021-04-02 11:48 UTC
Labels: bug
